name: 'Validate PR Title'
description: 'Github action to enforce Pull Request title conventions'
author: 'Prashant Kumar'

inputs:
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
