name: 'Conventional Pull Request Validator'
description: 'Github action to enforce Pull Request to follow commitlint convention'
author: 'Prashant Kumar'

inputs:
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
